### PR TITLE
Add sync after mv

### PR DESCRIPTION
**Pull request by lookfirst**
Pr for #22

### CODE REVIEW

**Comment by lookfirst** [comment]
@jpillora ping?

**Comment by jpillora** [comment]
Do all posix systems have "sync" ? Sorry haven't had time to look into this
yet

**Comment by lookfirst** [comment]
@jpillora Linux (coreutils), BusyBox (what I care about) and Darwin do.

https://www.freebsd.org/cgi/man.cgi?query=sync&sektion=8

`A sync utility appeared in	Version	4 AT&T UNIX.`

Maybe not posix standard, but been around forever now.

**Comment by lookfirst** [comment]
@jpillora Ping?

**Comment by jpillora** [comment]
Thanks @lookfirst Sorry for the delay

**Pull request merged**
